FROM ubuntu:16.04

ARG ENV

RUN apt-get update --fix-missing && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        pkg-config \
        openjdk-8-jre-headless \
	    python3-dev \
	    python3-pip \
        && \
    apt-get clean

RUN pip3 install --upgrade pip
RUN pip3 install setuptools wheel
RUN pip3 install sanic-openapi==0.4.0

RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

RUN mkdir /tmp/cador
COPY cador-build /tmp/cador

RUN cd /tmp && cd cador && python3 setup.py bdist_wheel &&  python3 setup.py sdist \
	&& pip3 install dist/*cador*whl && cd /tmp && rm -rf cador

CMD python3 -c
